### ISSUE TITLE
Bazel no longer builds Tensorflow properly

### ISSUE THREAD

**Issue by yngtodd** [olcf/SingularityTools#12]
Tried building a container with Tensorflow 1.3, following the [tensorflow.def](https://github.com/olcf/SingularityTools/blob/master/Titan/Tensorflow/tensorflow.def) definition for Titan, but it seems that recent Updates to Bazel are breaking inside the container:

```
+ cd tensorflow
+ git checkout tags/v1.3.0
Note: checking out 'tags/v1.3.0'.

# ...

HEAD is now at 9e76bf3... Merge pull request #12342 from jart/r1.3-tensorboard-notes
+ ./configure
Extracting Bazel installation...
.................................
You have bazel 0.9.0 installed.
./configure: line 669: /usr/local/cuda/extras/demo_suite/deviceQuery: No such file or directory
Configuration finished
+ bazel build -c opt --copt=-mavx --copt=-msse4.1 --copt=-msse4.2 --incompatible_disallow_uncalled_set_constructor=false --config=cuda tensorflow/tools/pip_package:build_pip_package
Loading:

Loading: 0 packages loaded

Loading: 0 packages loaded

ERROR: /root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/io_bazel_rules_closure/closure/private/defs.bzl:27:16: The function 'set' has been removed in favor of 'depset', please use the latter. You can temporarily refer to the old 'set' constructor from unexecuted code by using --incompatible_disallow_uncalled_set_constructor=false

ERROR: error loading package '': Extension file 'closure/private/defs.bzl' has errors

ERROR: error loading package '': Extension file 'closure/private/defs.bzl' has errors
```

Following the recommendation from the error, I tried setting `--incompatible_disallow_uncalled_set_constructor=false` here: https://github.com/yngtodd/singularity/blob/master/Singularity#L120. 

However, I am still running into errors. Do you know which Bazel version number was originally working with Tensorflow 1.3?

**Comment by AdamSimpson** [comment]
This repository is being replaced by [container-recipes](https://github.com/olcf/container-recipes/blob/master/titan/tensorflow/1.3.0/Dockerfile). I have a working build of tensorflow/1.3.0 there which is the highest version that supports cuda/7.5.
